wandb_version: 1

batch_size:
  value: 21
dataset_color:
  value: red
epochs:
  value: 83
lr:
  value: 0.002874518808788441
method:
  value: bayes
model_name:
  value: Alexnet
momentum:
  value: 0.33931019023542536
num_classes:
  value: 3
num_workers:
  value: 1
use_pretrained:
  value: 'True'
