wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
batch_size:
  desc: null
  value: 6
dataset_color:
  desc: null
  value: red
epochs:
  desc: null
  value: 80
lr:
  desc: null
  value: 0.0039657856310752505
method:
  desc: null
  value: bayes
model_name:
  desc: null
  value: Alexnet
momentum:
  desc: null
  value: 1.0946596166447569
num_classes:
  desc: null
  value: 3
num_workers:
  desc: null
  value: 1
use_pretrained:
  desc: null
  value: 'False'
