wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
batch_size:
  desc: null
  value: 13
dataset_color:
  desc: null
  value: red
epochs:
  desc: null
  value: 30
lr:
  desc: null
  value: 0.0004559324304858932
method:
  desc: null
  value: bayes
model_name:
  desc: null
  value: VGG11_bn
momentum:
  desc: null
  value: 3.164956093640236
num_classes:
  desc: null
  value: 3
num_workers:
  desc: null
  value: 1
use_pretrained:
  desc: null
  value: 'True'
