wandb_version: 1

batch_size:
  value: 2
dataset_color:
  value: red
epochs:
  value: 69
lr:
  value: 0.0038463344721200517
method:
  value: bayes
model_name:
  value: Resnet18
momentum:
  value: 0.42532138179995593
num_classes:
  value: 3
num_workers:
  value: 4
use_pretrained:
  value: 'True'
