wandb_version: 1

batch_size:
  value: 26
dataset_color:
  value: white
epochs:
  value: 57
lr:
  value: 0.0025079846730727247
method:
  value: bayes
model_name:
  value: Alexnet
momentum:
  value: 3.221261523888837
num_classes:
  value: 3
num_workers:
  value: 4
use_pretrained:
  value: 'False'
