wandb_version: 1

batch_size:
  value: 10
dataset_color:
  value: white
epochs:
  value: 44
lr:
  value: 0.0030420923170994714
method:
  value: bayes
model_name:
  value: Resnet18
momentum:
  value: 0.43069527193046325
num_classes:
  value: 3
num_workers:
  value: 4
use_pretrained:
  value: 'True'
