wandb_version: 1

batch_size:
  value: 4
dataset_color:
  value: white
epochs:
  value: 91
lr:
  value: 0.0019229579722750386
method:
  value: bayes
model_name:
  value: Squeezenet
momentum:
  value: 2.3089890287953607
num_classes:
  value: 3
num_workers:
  value: 4
use_pretrained:
  value: 'False'
