wandb_version: 1

batch_size:
  value: 22
dataset_color:
  value: white
epochs:
  value: 29
lr:
  value: 0.002233361838159157
method:
  value: bayes
model_name:
  value: VGG11_bn
momentum:
  value: 2.9573058482015795
num_classes:
  value: 3
num_workers:
  value: 0
use_pretrained:
  value: 'False'
