wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
batch_size:
  desc: null
  value: 9
dataset_color:
  desc: null
  value: white
epochs:
  desc: null
  value: 44
lr:
  desc: null
  value: 0.0017444245019038421
method:
  desc: null
  value: bayes
model_name:
  desc: null
  value: Resnet18
momentum:
  desc: null
  value: 0.43908177198309417
num_classes:
  desc: null
  value: 3
num_workers:
  desc: null
  value: 4
use_pretrained:
  desc: null
  value: 'True'
