wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
batch_size:
  desc: null
  value: 22
dataset_color:
  desc: null
  value: white
epochs:
  desc: null
  value: 29
lr:
  desc: null
  value: 0.002233361838159157
method:
  desc: null
  value: bayes
model_name:
  desc: null
  value: VGG11_bn
momentum:
  desc: null
  value: 2.9573058482015795
num_classes:
  desc: null
  value: 3
num_workers:
  desc: null
  value: 0
use_pretrained:
  desc: null
  value: 'False'
