wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
batch_size:
  desc: null
  value: 10
dataset_color:
  desc: null
  value: white
epochs:
  desc: null
  value: 24
lr:
  desc: null
  value: 0.001044579994271343
method:
  desc: null
  value: bayes
model_name:
  desc: null
  value: Resnet18
momentum:
  desc: null
  value: 2.4887663598248744
num_classes:
  desc: null
  value: 3
num_workers:
  desc: null
  value: 2
use_pretrained:
  desc: null
  value: 'False'
